# -*- coding: utf-8 -*-
"""PROYECTO PROCESOS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rj5jqSggWBxGSi6dMgrkFVDXqgxUiCcM
"""

21

from bs4 import BeautifulSoup #SI se paga por algo, tienen que entregarte el producto con los requerimiento que se pidió
from wordcloud import WordCloud, STOPWORDS
import requests

stack = 'https://es.stackoverflow.com/users/'
user = input('inserte ID:')
stack = stack + str(user)+"?tab=tags"
link = requests.get(stack)
html= BeautifulSoup(link.content,'html.parser')
users= html.find_all('a',class_='post-tag')

etiquetas = list()
for i in users:
    etiquetas.append(i.text)


print(etiquetas)

with open("proyecto.txt","w")as file:
      file.write(str(etiquetas))

stopwords = []


doc = open("proyecto.txt","r+")
datos = doc.read().replace("'","")
print(doc.read())


var_wordcloud = WordCloud(width=500,height=500,background_color='white',stopwords=stopwords,min_font_size=5,max_font_size=500).generate(datos)
var_wordcloud.to_file("/content/img.png")
img = var_wordcloud.to_image()

img